name: Minha primeira pipeline

on:
  push:
    branches:
      - main

jobs:
  executar-java:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Compilar
        run: javac Main.java

      - name: Executar
        run: java Main
